env:
  LC_ALL: "en_US.UTF-8"

steps:
  - label: 'Update docs'
    command:
      - nix-build -A maintainer-scripts.update-docs -o update-docs.sh
      - ./update-docs.sh
    agents:
      system: x86_64-linux
    branches: "master"

  - label: 'Check that jobset will evaluate in Hydra'
    command:
      - nix-build -A maintainer-scripts.check-hydra -o check-hydra.sh
      - ./check-hydra.sh 0
      - ./check-hydra.sh 1
      - ./check-hydra.sh 2
      - ./check-hydra.sh 3
    agents:
      system: x86_64-linux

  - label: 'Check Stylish Haskell'
    command: 'nix-shell --run .buildkite/check-stylish.sh'
    agents:
      system: x86_64-linux